### ISSUE TITLE
rename @private to @nullable and @hide to @skip

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#1]
What you are actually doing with `//@private` is making it nullable. It would make sense to rename the `@hide` to `@skip` as well IMHO.
WDYT?

**Comment by YassinEldeeb** [comment]
That's actually a lot better names, don't judge my names, It's pretty terrible look at the package name "prisma-typegraphql-types-generator" 😂😂

**Comment by YassinEldeeb** [comment]
Thank you for your namings, they're a lot better.

Published the new version 1.0.10 with the new updates.

**Comment by capaj** [comment]
Thanks! That was much faster than I anticipated.
I am glad you liked the names I suggested.
Maybe just next time when doing breaking changes like this keep in mind to do one of these 2:
- bump major version
- keep the old names as deprecated until a major bump occurs

BTW I really like how simple the code is. Much less complex than `typegraphql-prisma`.
