### ISSUE TITLE
/usr/bin/env: ‘node\r’: No such file or directory

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#2]
I am getting
```
npx prisma-typegraphql-types-generator
/usr/bin/env: ‘node\r’: No such file or directory
```

when I try to run on ubuntu.
Are you developing on windows? Seems like this is a line ending issue like here:
https://github.com/docsifyjs/docsify-cli/issues/78

maybe adding a `.editorconfig` could fix this.

**Comment by YassinEldeeb** [comment]
yep I'm on windows, I'll try using it with WSL to produce the issue and think of a solution

**Comment by capaj** [comment]
I have wroked around this problem just by editing my `node_modules/prisma-typegraphql-types-generator/dist/bin.js`
and switching to `LF` from `CRLF`.
I have bumped into another issue though. The process just hangs up-
```
npx prisma-typegraphql-types-generator
prisma:info Prisma Typegraphql Types Generator:Registered

```

I can close it by sending an interrupt, but nothing is generated.

**Comment by YassinEldeeb** [comment]
yeah so that means that you've run the package yourself and It wasn't invoked by prisma.

**Comment by YassinEldeeb** [comment]
only the files will be generated when prisma is the one running the generator

**Comment by capaj** [comment]
Interesting. Will try that.

**Comment by YassinEldeeb** [comment]
sadly I don't have access to ubuntu rn, can you please try that.

`yarn add prisma-typegraphql-types-generator@latest` or
`npm i prisma-typegraphql-types-generator@latest` 

then use this
```prisma
  provider = "node_modules/prisma-typegraphql-types-generator"
```

**Comment by capaj** [comment]
give me 10-15 minutes

**Comment by YassinEldeeb** [comment]
cause I think the problem is caused due to  running the package from npx and the unix format.

**Comment by capaj** [comment]
I am not sure why do you want me to test it again. Latest version on NPM is still 1.0.10 which is the one I am using.

**Comment by YassinEldeeb** [comment]
yeah the solution is not with testing with the latest version, It's with depending on installed package in node_modules instead of loading it from npx.

**Comment by YassinEldeeb** [comment]
did you tried with sudo cause It's telling "Permission denied"

**Comment by capaj** [comment]
No, it's not a good practice to invoke npm scripts with sudo.
I have never seen an npm/yarn script which would require sudo.

**Comment by YassinEldeeb** [comment]
but then why the error is pointing to "Permission denied"?

**Comment by YassinEldeeb** [comment]
oh yeah yeah yeah sorry

**Comment by YassinEldeeb** [comment]
I forgot the "node" before it

provider = "node node_modules/prisma-typegraphql-types-generator"

**Comment by YassinEldeeb** [comment]
did that work?

**Comment by capaj** [comment]
yes that works. TIL that typescript outputs line ending depending on the system where you run it. I would prefer `LF` always and only use `CLRF` when overriden.

**Comment by capaj** [comment]
I have opened a PR, because that `bin` file would still cause problems for people on unix based OSes

**Comment by YassinEldeeb** [comment]
merged you PR, Is it working properly now?

**Comment by YassinEldeeb** [comment]
It's working just fine as it was before on Windows, hope using LF line endings solved the issue on unix based systems.

**Comment by capaj** [comment]
tested with ```"prisma-typegraphql-types-generator": "^1.0.13",```
works nicely
