### ISSUE TITLE
create folder when it does not exist yet

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#3]
Error: ENOENT: no such file or directory, mkdir 'src/models/generated/'

is thrown when a folder does not exist yet. It would be nice if the generator could create it in such case.

**Comment by YassinEldeeb** [comment]
It can do that.
what operating system you're on?

![Screenshot 2021-11-17 134858](https://user-images.githubusercontent.com/72823042/142195246-cf184cff-1a6f-42e9-a45f-36abcd9abb84.png)

**Comment by YassinEldeeb** [comment]
and I kinda get where is the problem, is ubuntu paths looks like that "C:\\Users\yassin\\development" ?

![Screenshot 2021-11-17 135126](https://user-images.githubusercontent.com/72823042/142195574-2bfd4f7a-6e3b-4882-a07b-024260825116.png)

**Comment by YassinEldeeb** [comment]
This is the code responsible for making directories that doesn't exist
