### ISSUE TITLE
Bug: When splitted into scalar fields and object field, the second generated class does not have "@ObjectType" decorator 

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#32]
## Bug description
as per title

## Expected behavior
decorator is on both classes

**Comment by YassinEldeeb** [comment]
I was hundred percent sure there's a problem with this feature 😅
Thanks for noticing it 💚

**Comment by YassinEldeeb** [comment]
Fixed with version `1.22.17`
