### ISSUE TITLE
option to add custom suffix to generated models

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#6]
currently the models that are generated have the exact same name as models generated by prisma, so you end up having to do this:
```ts
import { WebInput } from '@prisma/client'
import { WebInput as WebInputGQL } from './models/generated/WebInput'
```

it would be gr8 if we could add some suffix/prefix to the generated class name like this:

```
generator PrismaTypeGraphQLTypesGenerator {
    provider     = "node node_modules/prisma-typegraphql-types-generator"
    modelsOutput = "./models/generated"
    enumsOutput  = "./models/types"
    useYarn      = true
    classNameSuffix = "GQL"
}
```
so then we could do:
```ts
import { WebInput } from '@prisma/client'
import { WebInputGQL } from './models/generated/WebInput'
```

**Comment by YassinEldeeb** [comment]
That could be a good use case that I didn't face in my [large project](https://github.com/YassinEldeeb/Blogs-Podcasts-Platform), 
coding it...

**Comment by YassinEldeeb** [comment]
Done 🎉!

you can use now 👇

```prisma
generator PrismaTypeGraphQLTypesGenerator {
  provider     = "node node_modules/prisma-typegraphql-types-generator"
  modelsOutput = "./models/generated"
  enumsOutput  = "./models/types"
  useYarn      = true
  exportedNameSuffix = "GQL" // optional
  // or
  exportedNamePrefix = "GQL"  // optional
}
```

**Comment by YassinEldeeb** [comment]
I said "Lots of configs to fit into any project" and this is a problem...having two exact exported names that should be fixed and this solution was pretty good "prefixing or add suffix to the end of exported names".

**Comment by capaj** [comment]
yes this helps in autocompletion as well

**Comment by YassinEldeeb** [comment]
you'll have to delete the old generated files cause the old imports will cause "modules not found"errors.

**Comment by capaj** [comment]
FYI this is a new feature. Typically in semver, if you release a new feature it is a minor version bump, not just patch version bump as you did. Will test this out.

**Comment by YassinEldeeb** [comment]
yeah totally forgot bumping it to 1.1.14.
