### ISSUE TITLE
Prisma Int type is generated as graphql Float

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#7]
Int should get generated as `TypeGraphQL.Int` ideally. That's how it gets generated with `prisma-typegraphql`

**Comment by YassinEldeeb** [comment]
yeah but doesn't matter, TypeGrapghql cast it to Int at the end of the day.

**Comment by YassinEldeeb** [comment]
oh yeah I got it it infers it to Float

**Comment by YassinEldeeb** [comment]
I'll go to private lessons and when I come back. I'll solve it.
