### ISSUE TITLE
add prettier at the end of code generation

### ISSUE THREAD

**Issue by capaj** [YassinEldeeb/prisma-tgql-types-gen#9]
Would be nice if we could run the generated code through prettier at the end, because when you keep the files in git they always get changed after a generation because the code style does not match.
I could disable prettier for those generated files, but given that this library supports editing these files it should support prettier compatible output as well.

**Comment by YassinEldeeb** [comment]
This feature was in my mind for a while now

**Comment by YassinEldeeb** [comment]
But did a poor quick search a few days ago to find a library that can take prettier config from your root project and apply formatting to it but couldn't find anything, but I barely searched, I should dive more to find out something that fit that, if you found any libraries for what I've described that would be nice to share it.

**Comment by capaj** [comment]
it would make sense to only run if prettier is detected, if not skip it.

Prettier code can be invoked programatically like this: https://prettier.io/docs/en/api.html

**Comment by YassinEldeeb** [comment]
Thank you for correcting me.

**Comment by YassinEldeeb** [comment]
Done ✔️

**Comment by YassinEldeeb** [comment]
now It can do:

1- Search for prettier config starting from your current working directory, this config file can be in whatever format and be wherever you want like very far away from your current working directory if your setup was a workspace.

2- apply the configs defined in your config file and apply it to the generated output.
